import {
	ArrowsClockwiseIcon,
	ArrowsLeftRightIcon,
	BankIcon,
	BuildingsIcon,
	BusIcon,
	CarIcon,
	CreditCardIcon,
	DotsThreeIcon,
	FilmSlateIcon,
	ForkKnifeIcon,
	GameControllerIcon,
	GlobeIcon,
	HeartbeatIcon,
	HouseIcon,
	type Icon,
	InvoiceIcon,
	PercentIcon,
	PiggyBankIcon,
	ReceiptIcon,
	ReceiptXIcon,
	ShieldCheckIcon,
	ShoppingBagIcon,
	ShoppingCartIcon,
	SlidersHorizontalIcon,
	SparkleIcon,
	TrendDownIcon,
	TrendUpIcon,
	TShirtIcon,
	WalletIcon,
} from "@phosphor-icons/react";
import type { Category, TransactionType } from "txcategorizer";

export const CATEGORY_ICONS: Record<Category, Icon> = {
	Dagligvare: ShoppingCartIcon,
	"Mat ute": ForkKnifeIcon,
	Hjem: HouseIcon,
	Underholdning: FilmSlateIcon,
	Gaming: GameControllerIcon,
	Abonnement: ArrowsClockwiseIcon,
	Netthandel: ShoppingBagIcon,
	Helse: HeartbeatIcon,
	Kosmetikk: SparkleIcon,
	Klær: TShirtIcon,
	Kreditt: CreditCardIcon,
	Transport: BusIcon,
	Bil: CarIcon,
	Bolig: BuildingsIcon,
	Boutgifter: InvoiceIcon,
	Forsikring: ShieldCheckIcon,
	Overføring: ArrowsLeftRightIcon,
	Inntekt: TrendUpIcon,
	Sparing: PiggyBankIcon,
	Diverse: ReceiptIcon,
	Annet: DotsThreeIcon,
};

export const TYPE_ICONS: Record<TransactionType, Icon> = {
	Varekjøp: CreditCardIcon,
	Visa: GlobeIcon,
	Betaling: ReceiptIcon,
	Giro: BankIcon,
	Overføring: ArrowsLeftRightIcon,
	Lønn: WalletIcon,
	Kontoregulering: SlidersHorizontalIcon,
	Nedbetaling: TrendDownIcon,
	Renter: PercentIcon,
	Omkostninger: ReceiptXIcon,
	Annet: DotsThreeIcon,
};
